name:                gg
version:             0.1.0.0
github:              "wenkokke/gg"
license:             BSD3
author:              "Wen Kokke"
maintainer:          "wen.kokke@gmail.com"
copyright:           "(c) 2017 Wen Kokke"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

description:         Please see the README on Github at <https://github.com/wenkokke/gg#readme>

dependencies:
- base >= 4.7 && < 5
- containers >= 0.5 && < 0.6
- data-ordlist >= 0.4 && < 0.5

library:
  source-dirs: src

executables:
  gg:
    main:                gg.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - gg

tests:
  gg-spec:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - gg
    - QuickCheck >= 2.10 && < 2.11
    - HUnit >= 1.6 && < 1.7
